DROP TABLE IF EXISTS `imdb_movies_links_full`;
CREATE TABLE `imdb_movies_links_full` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '电影id',
  `name` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '电影名称',
  `full_name` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '完整电影名称',
  `url` VARCHAR(300) NOT NULL DEFAULT '' COMMENT '电影链接',
  `completed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已完成:0=未完成,1=已完成',
  `spider_completed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已完成:0=未完成,1=已完成',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;