DROP TABLE IF EXISTS `imdb_movies`;
CREATE TABLE `imdb_movies` (
  `id` INT(10) NOT NULL AUTO_INCREMENT COMMENT '电影id',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '电影名称',
  `url` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '电影链接',
  `time` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '电影时长',
  `genre` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '电影类型',
  `release_time` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '电影上映时间',
  `intro` TEXT NOT NULL COMMENT '电影简介',
  `directors` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '电影导演',
  `writers` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '电影编剧',
  `starts` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '电影主演',
  `completed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已完成:0=未完成,1=已完成',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
